CREATE TABLE SUPERHEROES_BACKUP AS SELECT * FROM SUPERHEROES WHERE 1=2;

 -- creating the trigger
 CREATE OR REPLACE TRIGGER SH_BACKUP
 BEFORE INSERT OR DELETE OR UPDATE ON SUPERHEROES
 FOR EACH ROW
 ENABLE
 BEGIN
  IF INSERTING THEN
    INSERT INTO SUPERHEROES_BACKUP VALUES(:NEW.sh_name);
  ELSIF DELETING THEN
    DELETE FROM SUPERHEROES_BACKUP WHERE sh_name = :OLD.sh_name;
  ELSIF UPDATING THEN
    UPDATE SUPERHEROES_BACKUP SET sh_name = :NEW.sh_name WHERE sh_name = :OLD.sh_name;
  END IF;
 END;
 /
 
 -- testing the trigger
 
INSERT INTO SUPERHEROES VALUES('Zero');
INSERT INTO SUPERHEROES VALUES('Karen');

UPDATE SUPERHEROES SET sh_name = 'Lelouch' WHERE sh_name = 'Zero';

DELETE FROM SUPERHEROES WHERE sh_name = 'Karen';

SELECT * FROM SUPERHEROES;
SELECT * FROM SUPERHEROES_BACKUP;