SHOW USER;
/

CREATE TABLE STARTUP_AUDIT (
  EVENT_TYPE VARCHAR2(30),
  EVENT_DATE DATE,
  EVENT_TIME VARCHAR2(15)
);
/

-- the following was not accepted due to privilege

CREATE OR REPLACE TRIGGER TR_STARTUP_AUDIT
AFTER STARTUP ON DATABASE
BEGIN
  INSERT INTO STARTUP_AUDIT VALUES(
    ORA_SYSEVENT,
    SYSDATE,
    TO_CHAR(SYSDATE, 'hh24:mm:ss')
  );
END;
/

