-- Table 1
CREATE TABLE TRAINER (
  FULL_NAME VARCHAR2(20)
);

-- Table 2
CREATE TABLE SUBJECT (
  SUBJECT_NAME VARCHAR2(20)
);

-- inserting values to the two tables
INSERT INTO TRAINER VALUES('Neo Geo');
INSERT INTO SUBJECT VALUES('Oracle');

-- creating the view
CREATE VIEW VW_EXAMPLE AS
SELECT FULL_NAME, SUBJECT_NAME FROM TRAINER,SUBJECT;

SELECT * FROM VW_EXAMPLE;

-- the following should not work till now
INSERT INTO VW_EXAMPLE VALUES('Neo','Oracle');

-- instead of trigger
CREATE OR REPLACE TRIGGER TR_IO_INSERT
INSTEAD OF INSERT ON VW_EXAMPLE
FOR EACH ROW
BEGIN
  INSERT INTO TRAINER (FULL_NAME) VALUES (:NEW.FULL_NAME);
  INSERT INTO SUBJECT (SUBJECT_NAME) VALUES (:NEW.SUBJECT_NAME);
END;
/

-- the following should work after instead of trigger
INSERT INTO VW_EXAMPLE VALUES('Neo','Oracle');

-- checking
SELECT * FROM TRAINER;
SELECT * FROM SUBJECT;
