-- creating table and inserting values

CREATE TABLE STUDENTS
(
  STU_ID INTEGER PRIMARY KEY,
  FIRST_NAME VARCHAR2(8)
)

INSERT INTO STUDENTS
VALUES ( 1, 'Clark');

INSERT INTO STUDENTS
VALUES (2, 'Tony')

SELECT * FROM STUDENTS;

-- testing anchored type

DECLARE
  v_fname STUDENTS.FIRST_NAME%TYPE;
BEGIN
  SELECT FIRST_NAME INTO v_fname FROM STUDENTS
  WHERE STU_ID = 1;
  DBMS_OUTPUT.PUT_LINE(v_fname);
END;